# Generated by Django 3.2 on 2021-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210502_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='I agree to the T&C'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='datefield',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(upload_to='profile/user_pics'),
        ),
    ]
