# Generated by Django 3.2 on 2021-05-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210502_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='profile/user_pics'),
        ),
    ]
